apiVersion: cert-manager.io/v1

kind: Certificate
metadata:
  name: multi-k8s.naveejr.tk-tls
spec:
  secretName: multi-k8s.naveejr.tk
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: multi-k8s.naveejr.tk
  dnsNames:
    - multi-k8s.naveejr.tk
